services:
  openclaw:
    container_name: openclaw-happyladysace
    image: openclaw:local
    restart: unless-stopped
    networks:
      - 1panel-network
    environment:
      HOME: /home/node
      TERM: xterm-256color
      TZ: Asia/Shanghai
      HTTP_PROXY: http://127.0.0.1:10991
      HTTPS_PROXY: http://127.0.0.1:10991
      http_proxy: http://127.0.0.1:10991
      https_proxy: http://127.0.0.1:10991
    volumes:
      - /opt/openclaw/data/conf:/home/node/.openclaw
      - /opt/openclaw/data/workspace:/home/node/.openclaw/workspace
    ports:
      - 100.100.100.10:18789:18789
      - 100.100.100.10:18790:18790
    init: true
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--allow-unconfigured",
        "--bind",
        "lan",
        "--port",
        "18789"
      ]
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
